### ISSUE TITLE
Not working on cordova apps

### ISSUE THREAD

**Issue by miri-am** [vsivsi/meteor-file-job-sample-app#4]
Tested in iOS-Simulator. It is just creating image files of size 0.

**Comment by vsivsi** [comment]
You've provided so little detail, there's literally nothing I can do with this information.

**Comment by miri-am** [comment]
sending a reproduction in a moment

**Comment by miri-am** [comment]
Created simplified project, becaue  drag and drop does not work in apps. To replicate run with `meteor run ios`. I dont really know where the exact problem is, but hope this helps:

Reproduction: https://github.com/miri-am/file-collection-cordova-test

Screenshot of database: same image send from ios simulator (2) and from browser (1).
https://github.com/miri-am/file-collection-cordova-test/wiki

**Comment by vsivsi** [comment]
Hi, thanks for the info.  This is just a sample app that was written before the Cordova support was added to Meteor.  I really don't have time to work on this right now, and my current project isn't mobile...  

The zero size file isn't "corrupt". That is how file-collection files are initially created. Then the data is added when the actual upload occurs.  So it sounds like the upload isn't happening for some reason.  Either because your code to replace the drag-and-drop support for mobile is broken, or because resumable.js has some issue in the mobile environment (or some combination of those factors).

As I said, I really don't have time to work on this at the moment, and I'm fine if the sample app doesn't support Cordova, because it was never designed to...

If you solve the problem, I'd be happy to consider a PR, but otherwise I'm think I'm going to close this as a "won't fix".

**Comment by miri-am** [comment]
I dont think my code is broken, because it works fine in the browser environment. So it is probably the issue is with resumable on mobile support. I should have placed this in https://github.com/vsivsi/meteor-file-collection/issues anyways. Thanks for you anwer!
